#!/usr/bin/env node

const path = require("path")

require("task-env")({
  args: process.argv.slice(2),
  config: "river-config",
  root: path.resolve(__dirname, "../"),
  tasks: [
    require("./packages/encrypt-tasks")
  ],
})
