export const projectTypes = {
  Browser: [
    "babel",
    "babel-scripts",
    "babel-web",
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-scripts",
    "watchman-babel",
  ],
  Lerna: ["babel", "basics", "eslint", "husky"],
  React: [
    "babel",
    "babel-scripts",
    "babel-web-react",
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  Server: [
    "babel",
    "babel-node",
    "babel-scripts",
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-scripts",
    "watchman-babel",
  ],
  Task: [
    "babel",
    "babel-node",
    "babel-scripts",
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-scripts",
    "watchman-babel",
  ],
}
