export const projectTypes = {
  "Browser/Client Package": [
    "babel",
    "babel-scripts",
    "babel-web",
    "basics",
    "jest",
    "jest-scripts",
    "watchman-babel",
  ],
  "Lerna Monorepo": [
    "babel",
    "basics",
    "eslint",
    "husky",
    "lerna",
  ],
  "Next Package": [
    "babel",
    "basics",
    "jest",
    "jest-react",
    "jest-scripts",
    "next",
  ],
  "React Native Web Package": [
    "babel",
    "babel-scripts",
    "babel-web-react",
    "basics",
    "jest",
    "jest-react",
    "jest-scripts",
    "react-native-web",
    "watchman-babel",
  ],
  "React Package": [
    "babel",
    "babel-scripts",
    "babel-web-react",
    "basics",
    "jest",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  "Server/Task Package": [
    "babel",
    "babel-node",
    "babel-scripts",
    "basics",
    "jest",
    "jest-scripts",
    "watchman-babel",
  ],
}
